name: Metrics
on:
  # Aktualizacja automatyczna co 12 godzin
  schedule: [{cron: "0 */12 * * *"}]
  # Pozwala też uruchomić generowanie ręcznie w zakładce Actions
  workflow_dispatch:
  # Aktualizacja przy każdym pushu do gałęzi main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generowanie podstawowych statystyk i języków
        uses: lowlighter/metrics@latest
        with:
          # Tutaj podajemy sekret, który stworzyliśmy w Kroku 2
          token: ${{ secrets.METRICS_TOKEN }}

          # Podstawowe ustawienia wyglądu
          user: KsaweryTrebacz # <--- WPISZ TU SWÓJ NICK
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw # Twoja strefa czasowa
          
          # Wtyczka: Najczęściej używane języki (wykres)
          plugin_languages: yes
          plugin_languages_ignored: html, css # ignoruj proste języki
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # Wtyczka: Linie kodu (ile dodałeś/usunąłeś)
          plugin_lines: yes

          # Wtyczka: czas
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14 # Analiza z ostatnich 14 dni

          # Wtyczka: wykresy
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Pokazuj ostatnie pół roku (lub 'full-year')
